Update from template
mineiros-io/terraform-google-service-account pull request #30
Opened 2022-11-11 14:09 UTC by zied-elouaer

2022-11-14 09:54 UTC, waxb requested changes
changelog should reflect that the module drops support for `google` provider `3.x`

2022-11-14 09:54 UTC, waxb commented on .github/workflows/tests.yml
> +          version: 0.1.35
```suggestion
          version: 0.1.41
```

2022-11-14 09:54 UTC, waxb commented on README.tfdoc.hcl
> +            role               = "roles/iam.serviceAccountUser"
did `fmt` do this?

2022-11-14 11:06 UTC, waxb commented
please update the pr title

2022-11-14 11:08 UTC, waxb commented
please refresh `.gitignore` also

2022-11-14 14:18 UTC, waxb approved these changes
lgtm

2022-11-16 11:40 UTC, soerenmartius approved these changes
lgtm

2022-11-16 11:44 UTC, mariux approved these changes
lgtm

2022-11-16 11:54 UTC, merged